export const urduDictionary = {
  "the": "وہ",
  "a": "ایک",
  "an": "ایک",
  "is": "ہے",
  "are": "ہیں",
  "was": "تھا",
  "were": "تھے",
  "this": "یہ",
  "that": "وہ",
  "these": "یہ",
  "those": "وہ",

  "you": "تم",
  "he": "وہ",
  "she": "وہ",
  "it": "یہ",
  "we": "ہم",
  "they": "وہ",
  "my": "میرا",
  "your": "تمہارا",
  "his": "اس کا",
  "her": "اس کی",
  "its": "اس کا",
  "our": "ہمارا",
  "their": "ان کا",
  "in": "میں",
  "on": "پر",
  "at": "پر",
  "by": "کی طرف سے",
  "with": "کے ساتھ",
  "for": "کے لیے",
  "about": "کے بارے میں",
  "technology": "ٹیکنالوجی",
  "blog": "بلاگ",
  "article": "مضمون",
  "summary": "خلاصہ",
  "important": "اہم",
  "key": "کلیدی",
  "points": "نکات",
  "discusses": "بحث کرتا ہے",
  "explains": "وضاحت کرتا ہے",
  "how": "کیسے",
  "what": "کیا",
  "why": "کیوں",
  "when": "کب",
  "where": "کہاں",
  "can": "کر سکتا ہے",
  "could": "کر سکتا تھا",
  "will": "کرے گا",
  "would": "کرے گا",
  "should": "چاہیے",
  "might": "ہو سکتا ہے",
  "must": "ضرور",
  "here": "یہاں",
  "there": "وہاں",
  "some": "کچھ",
  "any": "کوئی",
  "all": "سب",
  "many": "بہت",
  "few": "کچھ",
  "most": "زیادہ تر",
  "other": "دوسرے",
  "such": "ایسے",
  "only": "صرف",
  "very": "بہت",
  "also": "بھی",
  "even": "بھی",
  "not": "نہیں",
  "but": "لیکن",
  "or": "یا",
  "and": "اور",
  "if": "اگر",
  "because": "کیونکہ",
  "as": "جیسا کہ",
  "while": "جبکہ",
  "which": "جو",
  "who": "جو",
  "whom": "جسے",
  "whose": "جس کا",
  "what": "کیا",
  "which": "کون سا",
  "when": "کب",
  "where": "کہاں",
  "why": "کیوں",
  "how": "کیسے",
  "first": "پہلا",
  "new": "نیا",
  "last": "آخری",
  "good": "اچھا",
  "bad": "برا",
  "big": "بڑا",
  "small": "چھوٹا",
  "high": "اونچا",
  "low": "نیچا",
  "next": "اگلا",
  "different": "مختلف",
  "same": "ایک ہی",
  "early": "جلدی",
  "young": "جوان",
  "old": "پرانا",
  "great": "عظیم",
  "important": "اہم",
  "long": "لمبا",
  "day": "دن",
  "week": "ہفتہ",
  "month": "مہینہ",
  "year": "سال",
  "today": "آج",
  "yesterday": "کل",
  "tomorrow": "کل",
  "time": "وقت",
  "work": "کام",
  "life": "زندگی",
  "people": "لوگ",
  "world": "دنیا",
  "home": "گھر",
  "school": "اسکول",
  "company": "کمپنی",
  "government": "حکومت",
  "country": "ملک",
  "problem": "مسئلہ",
  "question": "سوال",
  "fact": "حقیقت",
  "information": "معلومات",
  "development": "ترقی",
  "system": "نظام",
  "program": "پروگرام",
  "computer": "کمپیوٹر",
  "internet": "انٹرنیٹ",
  "website": "ویب سائٹ",
  "page": "صفحہ",
  "content": "مواد",
  "text": "متن",
  "image": "تصویر",
  "video": "ویڈیو",
  "audio": "آڈیو",
  "file": "فائل",
  "data": "ڈیٹا",
  "application": "ایپلیکیشن",
  "software": "سافٹ ویئر",
  "hardware": "ہارڈ ویئر",
  "server": "سرور",
  "network": "نیٹ ورک",
  "security": "سیکورٹی",
  "user": "صارف",
  "password": "پاس ورڈ",
  "email": "ای میل",
  "phone": "فون",
  "address": "پتہ",
  "name": "نام",
  "number": "نمبر",
  "price": "قیمت",
  "money": "پیسے",
  "percent": "فیصد",
  "order": "آرڈر",
  "service": "سروس",
  "product": "پروڈکٹ",
  "market": "مارکیٹ",
  "business": "کاروبار",
  "project": "منصوبہ",
  "meeting": "میٹنگ",
  "team": "ٹیم",
  "member": "رکن",
  "manager": "مینیجر",
  "employee": "ملازم",
  "customer": "گاہک",
  "client": "کلائنٹ",
  "sale": "سیل",
  "account": "اکاؤنٹ",
  "bank": "بینک",
  "card": "کارڈ",
  "payment": "ادائیگی",
  "tax": "ٹیکس",
  "law": "قانون",
  "policy": "پالیسی",
  "right": "حق",
  "left": "بائیں",
  "up": "اوپر",
  "down": "نیچے",
  "north": "شمال",
  "south": "جنوب",
  "east": "مشرق",
  "west": "مغرب",
  "top": "سب سے اوپر",
  "bottom": "نیچے",
  "side": "طرف",
  "front": "سامنے",
  "back": "پیچھے",
  "inside": "اندر",
  "outside": "باہر",
  "middle": "درمیان",
  "end": "آخر",
  "beginning": "شروع",
  "part": "حصہ",
  "piece": "ٹکڑا",
  "lot": "بہت",
  "bit": "تھوڑا",
  "more": "مزید",
  "less": "کم",
  "most": "سب سے زیادہ",
  "least": "کم سے کم",
  "better": "بہتر",
  "worse": "بدتر",
  "best": "بہترین",
  "worst": "بدترین",
  "true": "سچ",
  "false": "جھوٹ",
  "real": "حقیقی",
  "fake": "جعلی",
  "whole": "پورا",
  "half": "آدھا",
  "quarter": "چوتھائی",
  "third": "تیسرا",
  "fourth": "چوتھا",
  "fifth": "پانچواں",
  "sixth": "چھٹا",
  "seventh": "ساتواں",
  "eighth": "آٹھواں",
  "ninth": "نواں",
  "tenth": "دسواں",
  "hundred": "سو",
  "thousand": "ہزار",
  "million": "ملین",
  "billion": "ارب",
  "trillion": "کھرب",
  "zero": "صفر",
  "one": "ایک",
  "two": "دو",
  "three": "تین",
  "four": "چار",
  "five": "پانچ",
  "six": "چھ",
  "seven": "سات",
  "eight": "آٹھ",
  "nine": "نو",
  "ten": "دس",
  "twenty": "بیس",
  "thirty": "تیس",
  "forty": "چالیس",
  "fifty": "پچاس",
  "sixty": "ساٹھ",
  "seventy": "ستر",
  "eighty": "اسی",
  "ninety": "نوے",
  "hundred": "سو",
  "thousand": "ہزار",
  "million": "ملین",
  "billion": "ارب",
  "trillion": "کھرب",
  "first": "پہلا",
  "second": "دوسرا",
  "third": "تیسرا",
  "fourth": "چوتھا",
  "fifth": "پانچواں",
  "sixth": "چھٹا",
  "seventh": "ساتواں",
  "eighth": "آٹھواں",
  "ninth": "نواں",
  "tenth": "دسواں",
  "eleventh": "گیارہواں",
  "twelfth": "بارہواں",
  "thirteenth": "تیرہواں",
  "fourteenth": "چودہواں",
  "fifteenth": "پندرہواں",
  "sixteenth": "سولہواں",
  "seventeenth": "سترہواں",
  "eighteenth": "اٹھارہواں",
  "nineteenth": "انیسواں",
  "twentieth": "بیسواں",
  "thirtieth": "تیسواں",
  "fortieth": "چالیسواں",
  "fiftieth": "پچاسواں",
  "sixtieth": "ساٹھواں",
  "seventieth": "سترواں",
  "eightieth": "اسیواں",
  "ninetieth": "نوے واں",
  "hundredth": "سو واں",
  "thousandth": "ہزار واں",
  "millionth": "ملین واں",
  "billionth": "ارب واں",
  "trillionth": "کھرب واں",
  "once": "ایک بار",
  "twice": "دو بار",
  "thrice": "تین بار",
  "times": "بار",
  "again": "دوبارہ",
  "never": "کبھی نہیں",
  "always": "ہمیشہ",
  "often": "اکثر",
  "sometimes": "کبھی کبھی",
  "usually": "عام طور پر",
  "rarely": "شاذ و نادر",
  "seldom": "بہت کم",
  "frequently": "کثرت سے",
  "occasionally": "کبھی کبھار",
  "daily": "روزانہ",
  "weekly": "ہفتہ وار",
  "monthly": "ماہانہ",
  "yearly": "سالانہ",
  "annually": "سالانہ",
  "century": "صدی",
  "decade": "دہائی",
  "millennium": "ہزاریہ",
  "era": "دور",
  "age": "عمر",
  "period": "دور",
  "moment": "لمحہ",
  "hour": "گھنٹہ",
  "minute": "منٹ",
  "second": "سیکنڈ",
  "morning": "صبح",
  "afternoon": "دوپہر",
  "evening": "شام",
  "night": "رات",
  "midnight": "آدھی رات",
  "noon": "دوپہر",
  "dawn": "طلوع آفتاب",
  "dusk": "غروب آفتاب",
  "sunrise": "طلوع آفتاب",
  "sunset": "غروب آفتاب",
  "season": "موسم",
  "spring": "بہار",
  "summer": "گرمی",
  "autumn": "خزاں",
  "winter": "سردی",
  "weather": "موسم",
  "rain": "بارش",
  "snow": "برف",
  "wind": "ہوا",
  "storm": "طوفان",
  "cloud": "بادل",
  "fog": "دھند",
  "hail": "ژالہ باری",
  "lightning": "بجلی",
  "thunder": "گڑگڑاہٹ",
  "hurricane": "آندھی",
  "tornado": "بگولا",
  "earthquake": "زلزلہ",
  "flood": "سیلاب",
  "drought": "خشک سالی",
  "fire": "آگ",
  "ice": "برف",
  "water": "پانی",
  "air": "ہوا",
  "earth": "زمین",
  "sky": "آسمان",
  "moon": "چاند",
  "star": "ستارہ",

  "aluminum": "ایلومینیم",
  "be": "ہونا",
  "to": "کو، سے، پر ",
  "of": "کا، کی، کے",
  "and": "اور",
  "a": "ایک",
  "in": "میں",
  "that": "کہ، وہ",
  "have": "رکھنا",
  "I": "میں",
  "it": "یہ",
  "for": "کے لیے",
  "not": "نہیں",
  "on": "پر",
  "with": "کے ساتھ",
  "he": "وہ ",
  "as": "جیسا، جیسے",
  "you": "تم، آپ",
  "do": "کرنا",
  "at": "پر، میں",
  "this": "یہ",
  "but": "لیکن",
  "his": "اس کا ",
  "by": "سے، کے ذریعے",
  "from": "سے",
 
  "say": "کہنا",
  "her": "اس کی ",
  "she": "وہ ",
  "or": "یا",
  "an": "ایک",
  "will": "گا، گی، گے",
  "my": "میرا",
  "one": "ایک",
  "all": "سب",
  "would": "ہوگا",
  "there": "وہاں",
  "their": "ان کا",
  "what": "کیا",
  "so": "تو، اتنا",
  "up": "اوپر",
  "out": "باہر",
  "if": "اگر",
  "about": "کے بارے میں",
  "who": "کون",
  "get": "حاصل کرنا",
  "which": "کون سا",
  "go": "جانا",
  "me": "مجھے",
  "when": "جب",
  "make": "بنانا",
  "can": "سکنا",
  "like": "پسند کرنا",
  "time": "وقت",
  "no": "نہیں",
  "just": "بس، صرف",
  "him": "اسے (male)",
  "know": "جاننا",
  "take": "لینا",
  "people": "لوگ",
  "into": "میں",
  "year": "سال",
  "your": "آپ کا",
  "good": "اچھا",
  "some": "کچھ",
  "could": "سکتا تھا",
  "them": "انہیں",
  "see": "دیکھنا",
  "other": "دوسرا",
  "than": "سے",
  "then": "پھر",
  "now": "اب",
  "look": "دیکھو",
  "only": "صرف",
  "come": "آنا",
  "its": "اس کا",
  "over": "اوپر",
  "think": "سوچنا",
  "also": "بھی",
  "back": "پیچھے",
  "after": "بعد",
  "use": "استعمال کرنا",
  "two": "دو",
  "how": "کیسے",
  "our": "ہمارا",
  "work": "کام",
  "first": "پہلا",
  "well": "اچھا",
  "way": "طریقہ",
  "even": "بھی",
  "new": "نیا",
  "want": "چاہنا",
  "because": "کیونکہ",
  "any": "کوئی",
  "these": "یہ",
  "give": "دینا",
  "day": "دن",
  "most": "سب سے زیادہ",
  "us": "ہمیں",
  "eat": "کھانا",
  "drink": "پینا",
  "sleep": "سونے",
  "walk": "چلنا",
  "run": "بھاگنا",
  "talk": "بولنا",
  "listen": "سننا",
  "read": "پڑھنا",
  "write": "لکھنا",
  "learn": "سیکھنا",
  "teach": "پڑھانا",
  "work": "کام کرنا",
  "play": "کھیلنا",
  "buy": "خریدنا",
  "sell": "بیچنا",
  "open": "کھولنا",
  "close": "بند کرنا",
  "love": "محبت کرنا",
  "like": "پسند کرنا",
  "hate": "نفرت کرنا",
  "water": "پانی",
  "food": "کھانا",
  "house": "گھر",
  "car": "گاڑی",
  "book": "کتاب",
  "pen": "قلم",
  "friend": "دوست",
  "family": "خاندان",
  "school": "اسکول",
  "city": "شہر",
  "country": "ملک",
  "money": "پیسے",
  "job": "نوکری",
  "problem": "مسئلہ",
  "question": "سوال",
  "answer": "جواب",
  "big": "بڑا",
  "small": "چھوٹا",
  "happy": "خوش",
  "sad": "اداس",
  "good": "اچھا",
  "bad": "برا",
  "hot": "گرم",
  "cold": "ٹھنڈا",
  "fast": "تیز",
  "slow": "آہستہ",
  "new": "نیا",
  "old": "پرانا",
  "right": "صحیح",
  "wrong": "غلط",
  "hello": "ہیلو، السلام علیکم",
  "goodbye": "الوداع، خدا حافظ",
  "thank you": "شکریہ",
  "please": "براہ کرم",
  "sorry": "معذرت",
  "yes": "ہاں",
  "no": "نہیں",
  "maybe": "شاید",
  "I don't know": "مجھے نہیں پتہ",
  "How are you?": "آپ کیسے ہیں؟",
  "What is your name?": "آپ کا نام کیا ہے؟",
  "My name is...": "میرا نام... ہے",
   "once": "ایک بار",
  "you": "آپ",
  "keep": "رکھنا",
  "knocked": "گرایا گیا",
  "out": "باہر",
  "distractions": "توجہ ہٹانے والی چیزیں",
  "it": "یہ",
  "can": "سکتا",
  "make": "بنانا",
  "sense": "سمجھ",
  "to": "پر ",
  "say": "کہنا",
  "yes": "ہاں",
  "any": "کوئی",
  "opportunity": "موقع",
  "that": "جو",
  "could": "سکتا تھا",
  "potentially": "ممکنہ طور پر",
  "move": "لے جانا",
  "in": "میں",
  "right": "صحیح",
  "direction": "سمت",
  "may": "سکتا ہے",
  "try": "کوشش کرنا",
  "many": "بہت",
  "things": "چیزیں",
  "discover": "دریافت کرنا",
  "what": "کیا",
  "works": "کام کرتا ہے",
  "and": "اور",
  "enjoy": "پسند کرنا",
  "this": "یہ",
  "phase": "دور",
  "of": "کا ",
  "exploration": "دریافت",
  "can": "سکتا ہے",
  "be": "ہونا",
  "especially": "خاص طور پر",
  "important": "اہم",
  "at": "پر",
  "start": "شروع",
  "a": "ایک",
  "plan": "منصوبہ",
  "job": "نوکری",
  "career": "کیریئر",
  "particularly":"بالخصوص",
   "timeless": "ہمیشہ رہنے والا",
  "challenge": "چیلنج",
  "real": "حقیقی",
  "world": "دنیا",
  "is": "ہے",
  "help": "مدد",
  "less-talented": "کم باصلاحیت",
  "people": "لوگ",
  "transcend": "عبور کرنا",
  "their": "ان کا",
  "limitations": "حدود",
  "pondering": "غور کرنا",
  "all": "سب",
  "this": "یہ",
  "in": "میں",
  "context": "سیاق و سباق",
  "of": "کا",
  "my": "میرا",
  "post": "عہدہ",
  "as": "جیسے",
  "new": "نیا",
  "captain": "کپتان",
  "benfold": "بینفولڈ",
  "read": "پڑھنا",
  "some": "کچھ",
  "exit": "رخصتی",
  "surveys": "جائزے",
  "interviews": "انٹرویوز",
  "conducted": "منعقد کیے گئے",
  "by": "کے ذریعے",
  "military": "فوج",
  "to": "کے لیے",
  "find": "پتا لگانا",
  "out": "باہر",
  "why": "کیوں",
  "are": "ہیں",
  "leaving": "چھوڑ رہے",
  "assumed": "سمجھا",
  "low": "کم",
  "pay": "تنخواہ",
  "would": "ہوگا",
  "be": "ہونا",
  "first": "پہلا",
  "reason": "وجہ",
  "but": "لیکن",
  "truth": "حقیقت",
  "was": "تھی",
  "fifth": "پانچواں",
   "continue": "جاری رکھنا",
  "polishing": "نکھارنا",  "for": "کے لیے",
  "now": "اب",
  "i": "میں",
  "want": "چاہنا",
  "to": "کے لیے",
  "continue": "جاری رکھنا",
  "polishing": "نکھارنا",
  "my": "میرا",
  "craft": "ہنر",
  "with": "کے ساتھ",
  "writing": "تحریر",
  "television": "ٹیلیویژن",
  "before": "پہلے",
  "can": "سکتا ہے",
  "confidently": "اعتماد سے",
  "sell": "بیچنا",
  "myself": "خود کو",
  "potential": "ممکنہ",
  "film": "فلم",
  "investor": "سرمایہ کار",
  "stakes": "داؤ",
  "are": "ہیں",
  "exceedingly": "انتہائی",
  "high": "اونچا",
  "when": "جب",
  "it": "یہ",
  "comes": "آتا ہے",
  "films": "فلمیں",
  "and": "اور",
  "don’t": "نہیں",
  "get": "حاصل کرنا",
  "ahead": "آگے",
  "of": "کا",
  "just": "بس",
  "yet": "ابھی",
  "being": "ہونا",
  "an": "ایک",
  "expatriate": "پردیسی",
  "how": "کیسے",
  "do": "کرنا",
  "you": "آپ",
  "view": "دیکھنا",
  "challenges": "چیلنجز",
  "faced": "درپیش",
  "by": "کے ذریعے",
  "others": "دوسرے",
  "like": "جیسے",
  "in": "میں",
  "your": "آپ کا",
  "community": "برادری",
  "truth": "حقیقت",
  "was": "تھی",
  "fifth": "پانچواں"
};
export function translateToUrdu(text) {
  return text
    .split(/\s+/)
    .map((word) => {
      const plainWord = word.toLowerCase().replace(/[.,!?;:()]/g, "");
      const translation = urduDictionary[plainWord];

      const suffix = word.match(/[.,!?;:()]+$/);
      return translation ? translation + (suffix?.[0] || "") : word;
    })
    .join(" ");
}