import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        {children}
        <footer className="border-t border-gray-200 mt-12 pt-6 pb-8 text-sm text-gray-600 max-w-3xl mx-auto px-4">
          <p className="font-semibold mb-2">Blog Scraper Content Note:</p>
          <p>The blog content rendered within this layout is cleaned and stripped of the following:</p>
          <ul className="list-disc list-inside my-2 ml-4">
            <li>Headers, footers, navigation bars, sidebars</li>
            <li>Script, style tags, and hidden DOM elements</li>
            <li>Comment counts, share buttons, social links, WhatsApp prompts</li>
            <li>Duplicate titles, redundant metadata, or promotional overlays</li>
          </ul>
          <p>Only meaningful article content — paragraphs, quotes, and inline story text — is retained. This ensures a clean, reader-focused experience free from unnecessary clutter.</p>
        </footer>
      </body>
    </html>
  );
}
